name: Build site

on:
  push:
    branches:
      - master

jobs:
  build_site:
    name: Build site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: actions/checkout@v2
      with:
        repository: frewsxcv/hate-sites
        token: ${{ secrets.FREWSXCV_GITHUB_ACCESS_TOKEN }}
    - name: Setup Python
      uses: actions/setup-python@v2
    - name: Install pipenv
      run: python -m pip install pipenv
      working-directory: $GITHUB_WORKSPACE/who-hosts-hate
    - name: Installing project dependencies
      run: pipenv install
      working-directory: $GITHUB_WORKSPACE/who-hosts-hate
    - name: Generate site
      run: pipenv run python build.py ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }} --hate-sites-csv-path ../hate-sites/hate-sites.csv
      working-directory: $GITHUB_WORKSPACE/who-hosts-hate
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
        SINGLE_COMMIT: true
